Repository sergomen/pomogoo, pull requests merged in 2024-10, with the labels that each got.

#10 (fix): fix typo
  src/app/(time)/add-time/page.jsx
  src/app/(time)/update-time/page.jsx
  src/app/profile/page.jsx
Labels: nextjs, backend, hacktoberfest-accepted, deploy

#12 (feat): Add Board component to leaderboard page
  next.config.mjs
  src/app/leaderboard/page.jsx
  src/components/Board.jsx
  tailwind.config.js
Labels: nextjs, frontend, hacktoberfest-accepted

#18 Added filters and sort functionality to 'leaderboard' page. #14 issue
  src/app/leaderboard/page.jsx
  src/components/Board.jsx
Labels: hacktoberfest-accepted

#16 issue #13 - Add not-found page
  package-lock.json
  src/app/not-found.js
  src/app/not-found.module.css
Labels: hacktoberfest-accepted

#21 (feat): represents data for leaderboard page
  src/app/(time)/add-time/page.jsx
  src/app/api/time/new/route.js
  src/components/Board.jsx
  src/models/time.js
Labels: nextjs, backend, frontend, hacktoberfest-accepted

#22 (feat): Add Footer Component and styles for it
  src/app/layout.js
  src/components/Footer.jsx
  src/styles/globals.css
Labels: nextjs, frontend, hacktoberfest-accepted

#23 (feat): add about page
  public/assets/images/about.png
  src/app/about/page.jsx
Labels: nextjs, frontend, hacktoberfest-accepted
